select * from customers limit 10;

--1) What is the total revenue generated by male and female customers?
select gender, sum(purchase_amount) as revenue
from customers
group by gender;

--2) Which customers used a discount but still spent more then the varage purchase amount
select customer_id, purchase_amount
from customers
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customers);

--3) Which are the top 5 product with the highest review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as "Average product Rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4) Compare the average purchase Amount between standard and express shipping.
select shipping_type,
round(AVG(purchase_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

--5) Do Subscribed customer spend more? Compare average spend and total review 
--   between subscribeds and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customers
group by subscription_status
order by total_revenue, avg_spend desc;

--6) Which 5 products have the highest percentage of purchase with discount applied ?
select item_purchased,
round (100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

--7) Segment customers into new, Returning, and loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customers	
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

--8) What are the top 3 most purchased product within each category

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customers
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--10) What is the revenue contribution of each age group ?
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;










